include:
- compose.redis.yaml
- compose.apm.yaml
services:
  app:
    build: .
    env_file:
      - ./.env
    environment:
      REDIS_URL: redis://redis:6379/
      OTEL_SERVICE_NAME: chat-search
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://tempo:4317
      OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: grpc
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://prometheus:9090/api/v1/otlp/v1/metrics
      OTEL_EXPORTER_OTLP_METRICS_PROTOCOL: http/protobuf
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
