include:
- compose.redis.yaml
services:
  app:
    build: .
    env_file:
      - ./.env
    environment:
      REDIS_URL: redis://redis:6379/
    ports:
      - "8000:8000"
    depends_on:
    - redis
