services:
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
    - ./apm/tempo.yaml:/etc/tempo.yaml
    ports:
    - "14268:14268"  # jaeger ingest
    - "3200:3200"   # tempo
    - "9095:9095" # tempo grpc
    - "4317:4317"  # otlp grpc
    - "4318:4318"  # otlp http
    - "9411:9411"   # zipkin

  prometheus:
    image: prom/prometheus:latest
    command:
    - --config.file=/etc/prometheus.yaml
    - --web.enable-remote-write-receiver
    - --enable-feature=exemplar-storage
    - --enable-feature=otlp-write-receiver
    volumes:
    - ./apm/prometheus.yaml:/etc/prometheus.yaml
    ports:
    - "9090:9090"

  grafana:
    image: grafana/grafana:10.2.2
    volumes:
    - ./apm/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    - GF_AUTH_DISABLE_LOGIN_FORM=true
    - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    ports:
    - "3000:3000"
