services:
  redis:
    image: redis/redis-stack:6.2.6-v11
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      REDIS_ARGS: --save 60 1000 --appendonly yes
    volumes:
      - redis-data:/data
volumes:
  redis-data:
