apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${SERVICE}
spec:
  template:
    spec:
      containers:
      - image: ${IMAGE}
        ports:
        - containerPort: 8000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: ${OPENAI_API_KEY_SECRET_VERSION}
              name: ${OPENAI_API_KEY_SECRET_NAME}
