apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${SERVICE}
spec:
  template:
    spec:
      containers:
      - image: ${IMAGE}
        ports:
        - containerPort: 8000
        env:
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: ${AUTH_TOKEN_SECRET_VERSION}
              name: ${AUTH_TOKEN_SECRET_NAME}
        - name: LANGCHAIN_TRACING_V2
          value: "${LANGCHAIN_TRACING_V2}"
        - name: LANGCHAIN_PROJECT
          value: ${LANGCHAIN_PROJECT}
        - name: LANGCHAIN_API_KEY
          valueFrom:
            secretKeyRef:
              key: ${LANGCHAIN_API_KEY_SECRET_VERSION}
              name: ${LANGCHAIN_API_KEY_SECRET_NAME}
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: ${OPENAI_API_KEY_SECRET_VERSION}
              name: ${OPENAI_API_KEY_SECRET_NAME}
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              key: ${REDIS_URL_SECRET_VERSION}
              name: ${REDIS_URL_SECRET_NAME}
