apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${SERVICE}
spec:
  template:
    spec:
      containers:
      - image: ${IMAGE}
        ports:
        - containerPort: 8000
        startupProbe:
          httpGet:
            path: /health
            port: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
        env:
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: ${AUTH_TOKEN_SECRET_VERSION}
              name: ${AUTH_TOKEN_SECRET_NAME}
        - name: LANGCHAIN_TRACING_V2
          value: "${LANGCHAIN_TRACING_V2}"
        - name: LANGCHAIN_PROJECT
          value: ${LANGCHAIN_PROJECT}
        - name: LANGCHAIN_API_KEY
          valueFrom:
            secretKeyRef:
              key: ${LANGCHAIN_API_KEY_SECRET_VERSION}
              name: ${LANGCHAIN_API_KEY_SECRET_NAME}
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: ${OPENAI_API_KEY_SECRET_VERSION}
              name: ${OPENAI_API_KEY_SECRET_NAME}
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: ${OTEL_EXPORTER_OTLP_PROTOCOL}
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: ${OTEL_EXPORTER_OTLP_ENDPOINT}
        - name: OTEL_EXPORTER_OTLP_HEADERS
          valueFrom:
            secretKeyRef:
              key: ${OTEL_EXPORTER_OTLP_HEADERS_SECRET_VERSION}
              name: ${OTEL_EXPORTER_OTLP_HEADERS_SECRET_NAME}
        - name: OTEL_SERVICE_NAME
          value: ${OTEL_SERVICE_NAME}
        - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
          value: "${OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED}"
        - name: PYROSCOPE_SERVER_ADDRESS
          value: ${PYROSCOPE_SERVER_ADDRESS}
        - name: PYROSCOPE_BASIC_AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              key: ${PYROSCOPE_BASIC_AUTH_USERNAME_SECRET_VERSION}
              name: ${PYROSCOPE_BASIC_AUTH_USERNAME_SECRET_NAME}
        - name: PYROSCOPE_BASIC_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ${PYROSCOPE_BASIC_AUTH_PASSWORD_SECRET_VERSION}
              name: ${PYROSCOPE_BASIC_AUTH_PASSWORD_SECRET_NAME}
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              key: ${REDIS_URL_SECRET_VERSION}
              name: ${REDIS_URL_SECRET_NAME}
