apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chat-search.fullname" . }}
  labels:
    {{- include "chat-search.labels" . | nindent 4 }}
data:
  {{- .Values.dotenv.config | toYaml | nindent 2 }}
