apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chat-search.fullname" . }}
  labels:
    {{- include "chat-search.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.dotenv.secret }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
