tag:
- case_sensitive: false
  name: source
  no_index: false
  separator: ','
  sortable: false
- case_sensitive: false
  name: language
  no_index: false
  separator: ','
  sortable: false
text:
- name: title
  no_index: false
  no_stem: false
  sortable: false
  weight: 3.0
  withsuffixtrie: false
- name: description
  no_index: false
  no_stem: false
  sortable: false
  weight: 2.0
  withsuffixtrie: false
- name: content
  no_index: false
  no_stem: false
  sortable: false
  weight: 1.0
  withsuffixtrie: false
vector:
- algorithm: FLAT
  datatype: FLOAT32
  dims: 1536
  distance_metric: COSINE
  name: content_vector
