name: CICD

on:
  push:
    branches: [ main ]

env:
  GCLOUD_PROJECT: hemslo-chat-search
  GCLOUD_REGISTRY: us-west1-docker.pkg.dev
  GCLOUD_REPO: chat-search
  GITHUB_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: google-github-actions/auth@v2
        id: gcloud_auth
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          token_format: access_token
      - name: Login to Google Cloud Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GCLOUD_REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.gcloud_auth.outputs.access_token }}
      - name: Docker meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}
            ${{ env.GCLOUD_REGISTRY }}/${{ env.GCLOUD_PROJECT }}/${{ env.GCLOUD_REPO }}/${{ env.GCLOUD_REPO }}
          tags: |
            latest
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
